version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: nestjs-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_auth
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - nestjs-network

  # Redis (可选，用于缓存)
  redis:
    image: redis:7-alpine
    container_name: nestjs-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nestjs-network

  # NestJS 应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs-auth-app
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - nestjs-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  nestjs-network:
    driver: bridge
