global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nest-apps'
    static_configs:
      - targets: ['app:3002', 'app2:3003', 'app3:3004'] 
    metrics_path: '/api/v1/metrics'
    scheme: 'http'

 # Nginx指标
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 20s  # Nginx指标变化较慢，适当降低采集频率

    # RabbitMQ指标
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 20s  # RabbitMQ队列指标不需要高频采集  